// Defina um array de objetos de opção com valor e URL da imagem
const opcoesComImagens = [
    { valor: 'Argíla', imagem: 'imagens/mdfcores/argila_arauco.jpg' },
    { valor: 'Atenna', imagem: 'imagens/mdfcores/atenna_arauco.jpg' },
    { valor: 'Autentic', imagem: 'imagens/mdfcores/autentic_arauco.jpg' },
    { valor: 'Azul Sereno', imagem: 'imagens/mdfcores/azulsereno_arauco.jpg' },
    { valor: 'Amendola Rústica', imagem: 'imagens/mdfcores/amendolarustica_duratex.jpg' },
    { valor: 'Aurora', imagem: 'imagens/mdfcores/auroratrama_duratex.png' },
    { valor: 'Azul Astral', imagem: 'imagens/mdfcores/azulastral_duratex.jpg' },
    { valor: 'Amarelo Gema', imagem: 'imagens/mdfcores/amarelogema_eucatex.jpg' },
    { valor: 'Azul Mediterrâneo', imagem: 'imagens/mdfcores/azulmediterraneo_eucatex.png' },
    { valor: 'Acai Wood', imagem: 'imagens/mdfcores/acaiwood_floraplac.jpg' },
    { valor: 'Almeria', imagem: 'imagens/mdfcores/almeria_floraplac.jpg' },
    { valor: 'Amburana', imagem: 'imagens/mdfcores/amburana_floraplac.jpg' },
    { valor: 'Argos', imagem: 'imagens/mdfcores/argos_floraplac.jpg' },
    { valor: 'Beige', imagem: 'imagens/mdfcores/beige_arauco.jpg' },
    { valor: 'Beton', imagem: 'imagens/mdfcores/beton_arauco.jpg' },
    { valor: 'Branco Supremo', imagem: 'imagens/mdfcores/brancosupremo_arauco.jpg' },
    { valor: 'Bolero', imagem: 'imagens/mdfcores/bolero_duratex.jpg' },
    { valor: 'Branco Diamante', imagem: 'imagens/mdfcores/brancodiamante_duratex.jpg' },
    { valor: 'Brise', imagem: 'imagens/mdfcores/brise_duratex.jpg' },
    { valor: 'Branco Neve', imagem: 'imagens/mdfcores/branconeve_eucatex.png' },
    { valor: 'Barcelona', imagem: 'imagens/mdfcores/barcelona_floraplac.jpg' },
    { valor: 'Branco TX', imagem: 'imagens/mdfcores/branconordico_floraplac.png' },
    { valor: 'Branco TX Naval', imagem: 'imagens/mdfcores/branconordigonaval_floraplac.png' },
    { valor: 'Cacao', imagem: 'imagens/mdfcores/cacao_arauco.jpg' },
    { valor: 'Canela', imagem: 'imagens/mdfcores/canela_arauco.jpg' },
    { valor: 'Carvalho Ibiza', imagem: 'imagens/mdfcores/carvalhoibiza_arauco.jpg' },
    { valor: 'Cinza Cristal', imagem: 'imagens/mdfcores/cinzacristal_arauco.jpg' },
    { valor: 'Cinzel', imagem: 'imagens/mdfcores/cinzel_arauco.jpg' },
    { valor: 'Connect', imagem: 'imagens/mdfcores/connect_arauco.jpg' },
    { valor: 'Cumaru', imagem: 'imagens/mdfcores/cumaru_arauco.png' },
    { valor: 'Carvalho Teviso', imagem: 'imagens/mdfcores/carvalhoteviso_bernek.jpg' },
    { valor: 'Carvalho Hanover', imagem: 'imagens/mdfcores/carvalhohanover_duratex.jpg' },
    { valor: 'Carvalho Malva', imagem: 'imagens/mdfcores/carvalhomalva_duratex.jpg' },
    { valor: 'Cinza Sagrado Cris', imagem: 'imagens/mdfcores/cinzasagradocristallo_duratex.jpg' },
    { valor: 'Cinza Sagrado Essen', imagem: 'imagens/mdfcores/cinzasagradoessencial_duratex.jpg' },
    { valor: 'Cinza Italia', imagem: 'imagens/mdfcores/cinzaitalia_eucatex.jpg' },
    { valor: 'Cappucino Light', imagem: 'imagens/mdfcores/capuccinolight_floraplac.jpg' },
    { valor: 'Carbon', imagem: 'imagens/mdfcores/carbon_floraplac.jpg' },
    { valor: 'Carvalho Europeo', imagem: 'imagens/mdfcores/carvalhoeuropeo_floraplac.jpg' },
    { valor: 'Castanea', imagem: 'imagens/mdfcores/castanea_floraplac.jpg' },
    { valor: 'Castillo', imagem: 'imagens/mdfcores/castillo_floraplac.jpg' },
    { valor: 'Cement', imagem: 'imagens/mdfcores/cement_floraplac.jpg' },
    { valor: 'Cinza Cristal', imagem: 'imagens/mdfcores/cinzacristal_arauco.jpg' },
    { valor: 'Chandelier', imagem: 'imagens/mdfcores/chandelier_floraplac.jpg' },
    { valor: 'Chapele', imagem: 'imagens/mdfcores/chapele_floraplac.jpg' },
    { valor: 'Copenhagen', imagem: 'imagens/mdfcores/copenhagen_floraplac.jpg' },
    { valor: 'Cotton', imagem: 'imagens/mdfcores/cotton_floraplac.jpg' },
    { valor: 'Desert Rose', imagem: 'imagens/mdfcores/desertrose_eucatex.png' },
    { valor: 'Delicato', imagem: 'imagens/mdfcores/delicato_floraplac.jpg' },
    { valor: 'Durango', imagem: 'imagens/mdfcores/durango_floraplac.jpg' },
    { valor: 'Durban', imagem: 'imagens/mdfcores/durban_floraplac.png' },
    { valor: 'Ebano Carbone', imagem: 'imagens/mdfcores/ebano_floraplac.jpg' },
    { valor: 'Freijó Puro', imagem: 'imagens/mdfcores/freijopuro_duratex.jpg' },
    { valor: 'Fumê', imagem: 'imagens/mdfcores/fume_eucatex.jpg' },
    { valor: 'Fendi', imagem: 'imagens/mdfcores/fendi_floraplac.jpg' },
    { valor: 'Fendi Supermatte', imagem: 'imagens/mdfcores/fendisupermatte.jpg' },
    { valor: 'Fasano', imagem: 'imagens/mdfcores/fasano_floraplac.jpg' },
    { valor: 'Frassino Chiaro', imagem: 'imagens/mdfcores/frassinochiaro_floraplac.jpg' },
    { valor: 'Freijó Natural', imagem: 'imagens/mdfcores/freijonatural_floraplac.jpg' },
    { valor: 'Fresno Camurca', imagem: 'imagens/mdfcores/fresnocamurca_floraplac.jpg' },
    { valor: 'Grafito', imagem: 'imagens/mdfcores/grafito_arauco.jpg' },
    { valor: 'Gianduia Cristallo', imagem: 'imagens/mdfcores/gianduiacristallo_duratex.jpg' },
    { valor: 'Gianduia Trama', imagem: 'imagens/mdfcores/gianduiatrama_duratex.jpg' },
    { valor: 'Grafite', imagem: 'imagens/mdfcores/grafite_duratex.png' },
    { valor: 'Grafite Intenso', imagem: 'imagens/mdfcores/grafiteintenso_eucatex.png' },
    { valor: 'Gouthier', imagem: 'imagens/mdfcores/gouthier_floraplac.png' },
    { valor: 'Itapua', imagem: 'imagens/mdfcores/itapua_duratex.jpg' },
    { valor: 'Jequitiba', imagem: 'imagens/mdfcores/jequitiba_arauco.jpg' },
    { valor: 'Kiev', imagem: 'imagens/mdfcores/kiev_floraplac.jpg' },
    { valor: 'Lord', imagem: 'imagens/mdfcores/lord_arauco.png' },
    { valor: 'Louro Freijó', imagem: 'imagens/mdfcores/lourofreijo_arauco.png' },
    { valor: 'Lineo Têxtil', imagem: 'imagens/mdfcores/lineotextil_duratex.jpg' },
    { valor: 'Linum', imagem: 'imagens/mdfcores/linium_floraplac.jpg' },
    { valor: 'Metallic Suede', imagem: 'imagens/mdfcores/metallicsuede_bernek.jpg' },
    { valor: 'Mint', imagem: 'imagens/mdfcores/mint_duratex.jpg' },
    { valor: 'Malta', imagem: 'imagens/mdfcores/malta_floraplac.png' },
    { valor: 'Metallon', imagem: 'imagens/mdfcores/metallon_floraplac.jpg' },
    { valor: 'Milano', imagem: 'imagens/mdfcores/milano_floraplac.jpg' },
    { valor: 'Nogal Terracota', imagem: 'imagens/mdfcores/nogalterracota_arauco.jpg' },
    { valor: 'Nude', imagem: 'imagens/mdfcores/nude_arauco.jpg' },
    { valor: 'Nogal Amendoado', imagem: 'imagens/mdfcores/nogalamendoado_floraplac.jpg' },
    { valor: 'Nogueira Imperial', imagem: 'imagens/mdfcores/nogueiraimperialfloraplac.jpg' },
    { valor: 'Ouro Pálido', imagem: 'imagens/mdfcores/ouropalido_duratex.jpg' },
    { valor: 'Oxid Corten', imagem: 'imagens/mdfcores/oxidcorten_floraplac.jpg' },
    { valor: 'Palha', imagem: 'imagens/mdfcores/palha_duratex.jpg' },
    { valor: 'Pérola Urbana', imagem: 'imagens/mdfcores/perolaurbana_duratex.jpg' },
    { valor: 'Preto Brilhante', imagem: 'imagens/mdfcores/pretobrilhante_duratex.jpg' },
    { valor: 'Preto Ônix', imagem: 'imagens/mdfcores/pretoonix_eucatex.png' },
    { valor: 'Pangeia', imagem: 'imagens/mdfcores/pangeia_floraplac.jpg' },
    { valor: 'Pau Ferro Juca', imagem: 'imagens/mdfcores/pauferrojuca_floraplac.jpg' },
    { valor: 'Pietrasanta', imagem: 'imagens/mdfcores/pietrasanta_floraplac.jpg' },
    { valor: 'AtennaPreto TX', imagem: 'imagens/mdfcores/pretotx_floraplac.png' },
    { valor: 'Reali', imagem: 'imagens/mdfcores/reali_arauco.jpg' },
    { valor: 'Riga', imagem: 'imagens/mdfcores/riga_duratex.jpg' },
    { valor: 'Rosa', imagem: 'imagens/mdfcores/rosa_eucatex.jpg' },
    { valor: 'Robe Amaro', imagem: 'imagens/mdfcores/robeamaro_floraplac.jpg' },
    { valor: 'Sal Rosa', imagem: 'imagens/mdfcores/salrosa_arauco.jpg' },
    { valor: 'Sirena', imagem: 'imagens/mdfcores/sirena_duratex.jpg' },
    { valor: 'Safira', imagem: 'imagens/mdfcores/safira_floraplac.jpg' },
    { valor: 'Savanna', imagem: 'imagens/mdfcores/savanna_floraplac.jpg' },
    { valor: 'Titanio Trama', imagem: 'imagens/mdfcores/titaniotrama_duratex.jpg' },
    { valor: 'Titanio Cristalino', imagem: 'imagens/mdfcores/titaniocristallo_duratex.jpg' },
    { valor: 'Tesselati', imagem: 'imagens/mdfcores/tesselati_floraplac.jpg' },
    { valor: 'Verde Jade', imagem: 'imagens/mdfcores/verdejade_arauco.jpg' },
    { valor: 'Verde Real', imagem: 'imagens/mdfcores/verdereal_duratex.jpg' },
    { valor: 'Verde Bellagio', imagem: 'imagens/mdfcores/verdebellagio_eucatex.png' },
    { valor: 'Vermelho Scarlate', imagem: 'imagens/mdfcores/vermelhoscarlat_eucatex.jpg' },
    { valor: 'Versalhes', imagem: 'imagens/mdfcores/versalhes_floraplac.jpg' },
    { valor: 'Viena', imagem: 'imagens/mdfcores/viena_floraplac.png' },
    { valor: 'Wengue Suprema', imagem: 'imagens/mdfcores/wenguesuprema_floraplac.jpg' },
    // Adicione outras opções com imagens
];

const elementoSelect = document.getElementById('cor');

// Adicione ouvinte de evento para atualizar dinamicamente a imagem de fundo
elementoSelect.addEventListener('change', function() {
    const indiceSelecionado = this.selectedIndex;
    const opcaoSelecionada = opcoesComImagens[indiceSelecionado - 1]; // Subtrai 1 por causa da primeira opção desativada
    
    if (opcaoSelecionada) {
        this.style.backgroundImage = `url(${opcaoSelecionada.imagem})`;
    } else {
        this.style.backgroundImage = 'none';
    }
});